name: '[CI/CD] Application Workflow'

on:
  workflow_run:
    workflows: docker
    types: completed

jobs:
  build:
    # strategy:
    #   max-parallel: 3
    #   matrix:
    #     os: [ubuntu-latest, windows-latest]
    #     node-version: [12, 14, 16, 18, 20]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check credentials
        run: echo ${{ env.JWT_SECRET }}

      - name: Install all dependencies
        run: npm install

      - name: Run all test cases
        run: npm test
