name: '[CI/CD] Jest Basic Mocking'

on:
  push:
    branches: [main]

env:
  NODE_ENV: development

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install all dependencies
        run: npm install
      - name: Run all test cases
        run: npm test
