name: CI/CD Jest Basic Mocking

on:
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - closed
  push:
    branches:
      - main
  # workflow_run:
  #   workflows: [DOCKER_CI/CD]
  #   types: [completed]
  #   branches:
  #     - main
  # workflow_dispatch:
  #   inputs:
  #     branch:
  #       description: Pilih branch yang ingin anda deploy
  #       required: true
  #     environtment:
  #       description: Pilih environtment yang ingin anda deploy
  #       type: choice
  #       options:
  #         - production
  #         - staging
  #         - development
jobs:
  build:
    # strategy:
    #   max-parallel: 3
    #   matrix:
    #     os: [ubuntu-latest, windows-latest]
    #     node-version: [12, 14, 16, 18, 20]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Check credentials
        id: check
        run: echo ${{ env.JWT_SECRET }}

      - name: Install all dependencies
        run: npm ci

      - name: Run all test cases
        id: test
        run: npm test

      - name: Method Github
        run: |
          echo "${{ toJson(needs) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(steps) }}"
      #   run: |
      #     echo github: "${{ toJson(github) }}"
      #     echo github.event_name:  "${{ github.event_name }}"
      #     echo github.event: "${{ toJson(github.event) }}"
      #     echo github.ref: "${{ github.ref }}"
      #     echo github.ref_name: "${{ github.ref_name }}"
      #     echo github.ref_type: "${{ github.ref_type }}"
      #     echo github.job: "${{ github.job }}"
      #     echo github.actor: "${{ github.actor }}"
      #     echo github.actor_id: "${{ github.actor_id }}"
      #     echo job: "${{ toJson(job) }}"
      #     echo job.status: "${{ job.status }}"
      #     echo github.action_status: "${{ github.action_status }}"
      #     echo github.action_ref: "${{ github.action_ref }}"
      #     echo github.action_repository : "${{ github.action_repository }}"
      #     echo steps: "${{ toJson(steps) }}"
      #     echo github.path: "${{ github.path }}"
      #     echo secrets: ${{ toJson(secrets) }}
      #     echo env: "${{ toJson(env) }}"
      #     echo runs: "${{ toJson(runner) }}"

      - name: Previous Step Success
        if: ${{ success() }}
        run: echo "Previous Steps Success ${{ runner.name }}"

      - name: Previous Step Failure
        if: ${{ failure() }}
        run: echo "Previous Steps Failure ${{ runner.name }}"
