name: '[CI/CD] Jest Basic Mocking'

on:
  push:
    branches: [main]

jobs:
  build:
    # strategy:
    #   max-parallel: 3
    #   matrix:
    #     os: [ubuntu-latest, windows-latest]
    #     node-version: [12, 14, 16, 18, 20]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check credentials
        run: |
          echo ${{ env.NODE_ENV }}
          echo ${{ secrets.JWT_SECRET }}

      - name: Install all dependencies
        run: npm install

      - name: Run all test cases
        run: npm test
