name: '[CI/CD] Jest Basic Mocking'

on:
  push:
    branches: [main]

env:
  NODE_ENV: development

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  install:
    needs: clone
    runs-on: ubuntu-latest
    steps:
      - name: Install all dependencies
        run: npm install

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Run all test cases
        run: npm test
