name: Node.js CI

on:
  push:
    branches: [ main ]

env:
  NODE_ENV: development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Node & Npm Version
        run: |
            node -v
            npm -v

      - name: Install all dependencies
        run: npm i

      - name: Run all test
        run: npm test