name: Reusable Workflows Local

on:
  workflow_call:
    inputs:
      enterKeywords:
        description: Enter your input
        required: true
        type: string

jobs:
  print:
    runs-on: ubuntu-latest
    outputs:
      content: ${{ steps.hello.outputs.TEXT }}
    steps:
      - name: Print Hello Wordl!
        id: hello
        run: echo "TEXT=${{ inputs.enterKeywords }} - Included shared output" >> $GITHUB_OUTPUT
